import type { AppProps } from 'next/app'
import Head from 'next/head';
import { QueryClient, QueryClientProvider } from 'react-query';
import styled from 'styled-components'
import Header from '../components/Header';

const queryClient = new QueryClient();

export default function MyApp({ Component, pageProps }: AppProps) {
  return <Style>
    <Head>
      <title>Asce Football</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    <QueryClientProvider client={queryClient}>
      <Component {...pageProps} />
    </QueryClientProvider>
  </Style>
}

const Style = styled.div`
  font-family: Helvetica;
  font-size: 16px;
`
