import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useQuery, useQueryClient } from 'react-query'
import { getLeagues } from '../api/leagues'
import { LeagueResponse } from '../types'
import { leagues as mockLeagues } from '../__mocks__/data/leagues'

type Props = {
  leagues: LeagueResponse[];
}

const Home: NextPage<Props> = ({ leagues }) => {

  return (
    <div >
      <Head>
        <title>Asce Football</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Asce Football</h1>
        <ul>
          {leagues?.map(item => (
            <li key={item.league.id}>
              <Image 
                src={item.league.logo} 
                alt={`league-logo-${item.league.id}`}
                width={16}
                height={16}
              />
                {item.league.name}
            </li>
          ))}
        </ul>
      </main>

    </div>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {

  // const leagues = await getLeagues();
  const leagues: LeagueResponse[] = mockLeagues;

  return {
    props: { leagues }, // will be passed to the page component as props
  }
}

export default Home
