import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useQuery, useQueryClient } from 'react-query'
import { getLeagues } from '../api/leagues'
import { LeagueResponse } from '../types'

const Home: NextPage = () => {

  const queryCLient = useQueryClient()

  const query = useQuery<LeagueResponse[], Error>('leagues', getLeagues)
  
  if(query.isLoading) {
    return <div>Loading...</div>
  }

  if(query.isError) {
    return <div>Error...</div>
  }

  return (
    <div >
      <Head>
        <title>Asce Football</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Asce Football</h1>
        <ul>
          {query?.data?.map(item => (
            <li key={item.league.id}>
              <Image 
                src={item.league.logo} 
                alt={`league-logo-${item.league.id}`}
                width={16}
                height={16}
              />
                {item.league.name}
            </li>
          ))}
        </ul>
      </main>

    </div>
  )
}

export default Home
